EPS: 22.0  #Maximum distance between points to be considered in the same neighborhood
MIN_SAMPLES: 2    #Minimum number of samples to perform DBSCAN clustering
TRAJECTORY_SRC_PATH: "data/trajectories.json" 
PLOT_DIST_MATRIX: False
SAVE_DIST_MATRIX_PATH: "output/Directed_Hausdorff_Distance_matrix.png"
SAVE_GROUPED_TRAJECTORIES_PATH: "output/Grouped_Trajectories.png"